#!/usr/bin/env python3
import os
import sys
from OOPbase64.base64 import Base64Converter


def main():
    try:
        infile = open(sys.argv[1], 'rb')
    except IndexError:
        print('Requires file to encode as argument.')
        quit()
    except FileNotFoundError:
        print(f'{sys.argv[1]} file not found.')
        quit()

    outfile = open(sys.argv[1].replace('.', '__') + '.b64txt', 'w')
    b64 = Base64Converter()
    outfile.write(b64.encode(infile))

    infile.close()
    outfile.close()


if __name__ == '__main__':
    main()
