#!/usr/bin/env python3
import os
import sys
from OOPbase64.base64 import Base64Converter


def main():
    try:
        infile = open(sys.argv[1], 'r')
    except IndexError:
        print('Requires file to decode as argument.')
        quit()
    except FileNotFoundError:
        print(f'{sys.argv[1]} file not found.')
        quit()

    outfile = open(sys.argv[1][:-7].replace('__', '.'), 'wb')
    b64 = Base64Converter()
    outfile.write(b64.decode(infile))

    infile.close()
    outfile.close()


if __name__ == '__main__':
    main()
